### ISSUE TITLE
Follow through

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-2---android-activity-itsernestt#2]
https://github.com/MAD11877/mad21-practical-2---android-activity-itsernestt/blob/f8e1a06ffc24fabbeadae87790d6d96b36cf18ed/app/src/main/java/sg/edu/np/mad/week2madprac/MainActivity.java#L54-L59

Your event handler is empty at the moment
you have done the codes to toggle the text already.

Missing challenge question also

**Comment by itsernestt** [comment]
Removed event handler which was created by accident, also added challenge question (Scrollview)
